name: CI_test_v4
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: jeffrey-yc/dotNetCoreBMISample@v1
      - name: Run a one-line script
        run: echo Hello, world!
